# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cdcbc455192a6cd198ff6bb009a0d283d4c95263447132f44525743767b85e59856d4975c7bd5c20999575bf2ec5e6e7bd43b66d5ebe86144e61320ff87076c5

test:
  secret_key_base: 3419e0db4ee9e1fdb1f61581c11b1377970097b0dfbf4f3cec37f2966fbb7b78b0edb954333ddc0b266d0d4e3c1d8755ffdcc3b5e75927d2c0c06144ba6d424f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
